// Small finite-algebra helpers for the ch5 explainers. Everything is computed from Zn.

export const gcd = (a, b) => (b ? gcd(b, a % b) : a);
export const isPrime = (n) => { if (n < 2) return false; for (let i = 2; i * i <= n; i++) if (n % i === 0) return false; return true; };

export const znTable = (n, op) =>
  Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => (op === "+" ? (i + j) % n : (i * j) % n)));

// nonzero a that have a nonzero partner b with a*b = 0 (mod n)
export function zeroDivisors(n) {
  const out = [];
  for (let a = 1; a < n; a++) for (let b = 1; b < n; b++) if ((a * b) % n === 0) { out.push(a); break; }
  return out;
}

// units = elements coprime to n (they have a multiplicative inverse)
export const units = (n) => { const u = []; for (let a = 1; a < n; a++) if (gcd(a, n) === 1) u.push(a); return u; };

// additive subgroup / ideal generated by d in Zn (multiples of d, when d | n)
export const idealOf = (n, d) => { const s = []; for (let k = 0; k < n; k += d) s.push(k); return s; };
