// Builds public/data/biology.json from the verified Biology master/practice notes
// (MAKAUT BSC401 "Biology for Engineers"). Same shape as the other subjects' data so the
// game's lessons / skirmish / boss / walkthroughs all work. Run: node tools/build-biology.mjs
import { writeFileSync } from "fs";

const mcq = (n, question, opts, answer, years = [], model = false) => ({
  n: String(n), question,
  options: Object.entries(opts).map(([label, text]) => ({ label, text })),
  answer, asPrinted: false, years, model,
});
const qa = (n, question, answer, years = [], model = false) => ({ n: String(n), question, answer, years, model });
const con = (title, body) => ({ title, body });

const chapters = [
  {
    id: "ch1", num: 1, title: "Biology for Engineers", fullTitle: "Biology for Engineers — Module 1: Introduction",
    concepts: [
      con("What biology studies", "Biology is the natural science of life and living organisms: their structure, chemistry, physiology, development and evolution. Three unifying ideas run through it: the cell is the basic unit of life, the gene is the basic unit of heredity, and evolution is the engine that creates and removes species. Living organisms are open systems that take in energy to maintain a stable internal state (homeostasis)."),
      con("Why biology matters to engineers", "The genomic and molecular revolutions (the Human Genome Project was published in 2003, identifying about 25,000 human genes) let us treat biological functions as biomolecular machines and their regulation as biomolecular circuits. That reframing links biology to engineering: central dogma as computing, signal transduction as an amplifier or switch, the cell cycle and blood-sugar control as feedback systems, and the immune system as computer security."),
      con("Biomimicry", "Biomimicry is innovation that solves human problems by emulating nature's time-tested patterns and strategies. Biomimetic designs are human-made devices that imitate nature. There are three levels: the Organism, its Behaviour, and the Ecosystem (mnemonic O-B-E). Examples: bird wings shaped aeroplane wings, the gecko foot inspired dry gecko tape, the lotus leaf inspired self-cleaning surfaces, and the eye inspired the camera."),
      con("Science vs engineering", "Science goes from a physical system to a descriptive model (theory) using the scientific method (hypothesis then experiment) to understand what is not yet understood. Engineering goes the opposite way, from a model (design) to a physical system using the design process (define a problem then prototype) to build new things from what is already understood. Science seeks understanding; engineering erects systems."),
      con("The eye as a camera", "The eye and a camera solve the same problem and map part for part. The cornea and lens focus light like the camera lens; the iris and pupil control how much light enters like the aperture; the retina captures the image and converts light to electrical impulses like the film or sensor; and the optic nerve carries the signal to the brain like a data cable."),
    ],
    mcqs: [
      mcq(1, "The basic unit of heredity is the", { a: "cell", b: "gene", c: "tissue", d: "organ" }, "b", [], true),
      mcq(2, "The three levels of biomimicry are organism, behaviour and", { a: "molecule", b: "ecosystem", c: "habitat", d: "cell" }, "b", [], true),
      mcq(3, "The Human Genome Project was published in", { a: "1999", b: "2001", c: "2003", d: "2008" }, "c", [], true),
    ],
    short: [
      qa(1, "What is biomimicry? State its three levels with one example.", "**Biomimicry** is an approach to innovation that solves human challenges by emulating nature's time-tested patterns and strategies (mimicking nature for technology). Its three levels are: (1) the **Organism** (e.g. a bird's body shape inspiring an aeroplane), (2) its **Behaviour**, and (3) the **Ecosystem**. Example: the gecko's foot inspired dry **gecko tape**, and the lotus leaf inspired self-cleaning surfaces.", [], true),
      qa(2, "Compare the eye with a camera.", "Both focus light to form an image. **Cornea + lens** act as the camera **lens** (focus light); the **iris/pupil** acts as the **aperture** (controls light entering); the **retina** acts as the **film/sensor** (captures the image and converts light to electrical impulses); and the **optic nerve** acts as the **data cable** carrying the signal to the brain.", [], true),
      qa(3, "Distinguish the scientific method from the engineering design process.", "**Science** moves from a physical system to a descriptive model (theory): it uses the **scientific method** (hypothesis then experiment) to understand what is not yet understood. **Engineering** moves the other way, from a model (design) to a physical system: it uses the **design process** (define the problem then prototype) to create new things from what is already understood.", [], true),
    ],
    long: [
      qa(1, "How will you convey that Biology is as important a scientific discipline as Mathematics, Physics and Chemistry?", "Biology is foundational because it explains life itself through three unifying ideas: the **cell** (unit of life), the **gene** (unit of heredity), and **evolution** (the engine of change). Like the other sciences it is quantitative and predictive.\n\nFor engineers it is now indispensable: the genomic and molecular revolutions (the **Human Genome Project**, published 2003, ~25,000 genes) let us treat biological functions as **biomolecular machines** and their regulation as **biomolecular circuits**. This created deep links with engineering:\n- **Information processing:** DNA stores and transmits information like a computer.\n- **Biological circuits:** the central dogma behaves like computation.\n- **Signal transduction:** protein-kinase cascades act as amplifiers and switches.\n- **Control systems:** the cell cycle and blood-sugar regulation are feedback loops.\n- **Sensors:** the immune system parallels computer security.\n- **Biomimicry:** nature inspires engineering (gecko tape, self-cleaning surfaces, efficient turbine blades).\n\nThus biology supplies both fundamental understanding of life and a rich design language for modern engineering, making it as important as mathematics, physics and chemistry.", [2022]),
    ],
  },
  {
    id: "ch2", num: 2, title: "Biological Classification", fullTitle: "Biology for Engineers — Module 2: Biological Classification",
    concepts: [
      con("Classification and its history", "Classification is the scientific arrangement of organisms into groups by similarities and differences. Aristotle made the first attempt; Linnaeus gave a two-kingdom system (Plantae, Animalia) and binomial nomenclature (a two-word Latin name, Genus + species, e.g. Homo sapiens). R.H. Whittaker (1969) gave the modern five-kingdom system."),
      con("The five kingdoms", "Whittaker's five kingdoms, classified by cell structure, body organisation, nutrition, reproduction and phylogeny: Monera (prokaryotic bacteria and archaea), Protista (unicellular eukaryotes like diatoms and protozoa), Fungi (eukaryotic, mostly saprophytic; four classes including the imperfect fungi or Deuteromycetes), Plantae (multicellular, chlorophyll, autotrophic) and Animalia (multicellular, no cell wall, holozoic). Viruses, viroids and lichens are not placed in this system."),
      con("Taxonomic hierarchy", "Organisms are ranked from broad to narrow: Kingdom, Phylum, Class, Order, Family, Genus, Species (mnemonic: King Philip Came Over For Good Soup). A species is a group that interbreeds and produces fertile offspring; a genus is a group of related species; a family groups related genera; an order groups related families; a phylum groups related classes (a major body-plan division)."),
      con("Prokaryotic vs eukaryotic cells", "Prokaryotes (bacteria, archaea) are small (0.2-2 micrometre), always unicellular, have no membrane-bound nucleus, carry circular naked DNA, have 70S ribosomes, lack mitochondria/ER/Golgi, and divide by binary fission. Eukaryotes (plant and animal cells) are larger (10-100 micrometre), can be multicellular, have a true nucleus, linear DNA with histones, 80S ribosomes, membrane-bound organelles, and divide by mitosis or meiosis."),
      con("Model organisms", "Model organisms are easy-to-study species that stand in for biology in general. E. coli (a bacterium, doubles every ~20 min, cheap, harmless lab strains) for molecular genetics; S. cerevisiae (baker's yeast, a single-celled eukaryote that divides by meiosis and does homologous recombination); D. melanogaster (fruit fly, short cycle, few chromosomes) for inheritance; C. elegans (a worm, transparent, a fixed 959 somatic cells) for development and apoptosis; A. thaliana (a plant, small genome); and M. musculus (mouse, close to humans) for disease models."),
      con("Excretion of nitrogenous waste", "Animals excrete nitrogen waste in three ways. Ammonotelic animals (aquatic: bony fish, tadpoles) excrete ammonia, the most toxic, needing the most water. Ureotelic animals (mammals including humans, adult amphibians) excrete urea, intermediate in toxicity. Uricotelic animals (insects, reptiles and birds) excrete uric acid, the least toxic, needing the least water (the white paste in bird droppings)."),
    ],
    mcqs: [
      mcq(1, "The five-kingdom classification was proposed by", { a: "Linnaeus", b: "Aristotle", c: "Whittaker (1969)", d: "Huxley" }, "c", [], true),
      mcq(2, "The ribosome in a prokaryotic cell is", { a: "80S", b: "70S", c: "50S", d: "60S" }, "b", [2022], false),
      mcq(3, "Imperfect fungi (Deuteromycetes) are fungi whose", { a: "asexual stage is absent", b: "sexual (perfect) stage is unknown", c: "cell wall is absent", d: "nucleus is absent" }, "b", [2022], false),
      mcq(4, "Trinomial nomenclature was proposed by", { a: "Linnaeus", b: "Whittaker", c: "Huxley & Stricklandt", d: "Aristotle" }, "c", [], true),
    ],
    short: [
      qa(1, "Differentiate between prokaryotic and eukaryotic cells.", "| Feature | Prokaryote | Eukaryote |\n|---|---|---|\n| Nucleus | Absent (no membrane) | Present (membrane-bound) |\n| Size | 0.2-2 micrometre | 10-100 micrometre |\n| DNA | Circular, naked | Linear, with histones |\n| Ribosome | **70S** | **80S** |\n| Organelles | Mitochondria/ER/Golgi absent | Present |\n| Division | Binary fission | Mitosis / Meiosis |\n| Examples | Bacteria, Archaea | Plant and animal cells |", [2022, 2019]),
      qa(2, "Explain Species, Genus, Phylum, Order and Family.", "These are taxonomic ranks (broad to narrow: Kingdom > Phylum > Class > Order > Family > Genus > Species).\n- **Species:** a group of organisms that interbreed and produce fertile offspring (the basic unit).\n- **Genus:** a group of closely related species.\n- **Family:** a group of related genera.\n- **Order:** a group of related families.\n- **Phylum:** a group of related classes (a major body-plan division).", [2019]),
      qa(3, "Differentiate ammonotelic, ureotelic and uricotelic organisms.", "These describe how animals excrete nitrogenous waste.\n- **Ammonotelic:** excrete **ammonia** (most toxic, needs most water); aquatic animals such as bony fish and tadpoles.\n- **Ureotelic:** excrete **urea** (intermediate); mammals (including humans) and adult amphibians.\n- **Uricotelic:** excrete **uric acid** (least toxic, needs least water); insects, reptiles and birds.", [2022]),
    ],
    long: [
      qa(1, "Give the characteristics of E. coli, S. cerevisiae and D. melanogaster as model organisms.", "**E. coli** is a Gram-negative, rod-shaped bacterium. It is single-celled (no ethical issues), doubles every ~20 minutes, grows on cheap simple media, has well-mapped genetics and harmless lab strains. It is the workhorse for molecular biology, cloning and gene expression.\n\n**S. cerevisiae (baker's yeast)** is a single-celled **eukaryote**. It has a short generation time (1.25-2 h), divides by **meiosis** (so it is usable for sexual genetics), is easily transformed, and undergoes **homologous recombination** for gene knock-in/knock-out. It bridges to higher eukaryotes.\n\n**D. melanogaster (fruit fly)** has a short life cycle, large offspring numbers and only four chromosome pairs, and is easy to culture. It is the classical model for inheritance, linkage and developmental genetics.", [2022]),
      qa(2, "Give the characteristics of C. elegans, A. thaliana and M. musculus as model organisms.", "**C. elegans** is a small transparent nematode worm with a fixed, fully mapped number of **959 somatic cells** and a known cell lineage, making it ideal for studying development and programmed cell death (apoptosis).\n\n**A. thaliana (thale cress)** is a small flowering plant with a small genome and a fast life cycle, the standard model for plant genetics.\n\n**M. musculus (mouse)** is a mammal genetically and physiologically close to humans, used to model human diseases and test treatments.", [2022]),
    ],
  },
  {
    id: "ch3", num: 3, title: "Genetics", fullTitle: "Biology for Engineers — Module 3: Genetics",
    concepts: [
      con("Genetic vocabulary", "Genetics is the study of genes, variation and heredity. A gene is a unit of heredity (a DNA segment coding a trait); an allele is an alternative form of a gene (T = tall, t = short). Genotype is the genetic makeup (Tt); phenotype is the observable trait (tall). Homozygous means two identical alleles (TT or tt); heterozygous means two different (Tt). A dominant allele is expressed in the heterozygote; a recessive one only when homozygous. A mutation is a sudden, heritable change in a gene."),
      con("Mendel's three laws", "Mendel's laws of inheritance: (1) Law of Dominance, in a heterozygote the dominant allele masks the recessive. (2) Law of Segregation (purity of gametes), the two alleles of a gene separate during gamete formation so each gamete carries only one. (3) Law of Independent Assortment, alleles of different genes assort independently. Segregation acts on alleles of the same gene; independent assortment acts across different genes."),
      con("Crosses and ratios", "A monohybrid cross Tt x Tt gives a genotypic ratio 1 TT : 2 Tt : 1 tt and a phenotypic ratio 3 tall : 1 short. A dihybrid cross RrYy x RrYy gives a 9 : 3 : 3 : 1 phenotypic ratio, demonstrating independent assortment. A test cross (with the homozygous recessive) reveals an unknown genotype."),
      con("Deviations from Mendel", "Several patterns modify simple Mendelian ratios. Incomplete dominance gives an intermediate (blended) phenotype (red x white snapdragon gives pink; 1:2:1). Co-dominance expresses both alleles fully (AB blood group). Epistasis is when one gene masks or modifies a non-allelic gene at a different locus, giving modified 9:3:3:1 ratios (e.g. coat colour in Labradors). Linkage (genes on the same chromosome inherited together) is an exception to independent assortment."),
      con("Mitosis vs meiosis", "Mitosis is one division producing two diploid daughter cells identical to the parent, used for growth and repair in somatic cells, with no crossing over (stages PMAT: Prophase, Metaphase, Anaphase, Telophase, then Cytokinesis). Meiosis is two divisions producing four haploid, genetically variable cells, used to form gametes in germ cells, with synapsis and crossing over in prophase I that generate variation."),
    ],
    mcqs: [
      mcq(1, "The phenotypic ratio of a monohybrid cross (Tt x Tt) is", { a: "1:2:1", b: "3:1", c: "9:3:3:1", d: "1:1" }, "b", [], true),
      mcq(2, "Four daughter cells are produced by", { a: "mitosis", b: "meiosis", c: "binary fission", d: "budding" }, "b", [], true),
      mcq(3, "Which is an exception to Mendel's laws?", { a: "Dominance", b: "Segregation", c: "Linkage", d: "Purity of gametes" }, "c", [2022], false),
      mcq(4, "Incomplete dominance in snapdragon (red x white) gives", { a: "all red", b: "all white", c: "pink (intermediate)", d: "9:3:3:1" }, "c", [], true),
    ],
    short: [
      qa(1, "State Mendel's three laws of heredity.", "**1. Law of Dominance:** in a heterozygote, the dominant allele masks the recessive one.\n**2. Law of Segregation (purity of gametes):** the two alleles of a gene separate during gamete formation, so each gamete carries only one allele.\n**3. Law of Independent Assortment:** alleles of different genes assort independently of one another during gamete formation.", [2019]),
      qa(2, "Differentiate between mitosis and meiosis.", "| Feature | Mitosis | Meiosis |\n|---|---|---|\n| Purpose | Growth, repair | Gamete formation |\n| Divisions | One | **Two** |\n| Daughter cells | 2, diploid (2n) | 4, haploid (n) |\n| Genetic identity | Identical to parent | Variable |\n| Crossing over | Absent | **Present** (prophase I) |\n| Where | Somatic cells | Germ cells |", [2022, 2019]),
      qa(3, "Explain epistasis with an example.", "**Epistasis** is the interaction between two **non-allelic** genes in which one gene masks or suppresses the expression of another at a different locus, giving a modified 9:3:3:1 ratio (such as 9:3:4 or 12:3:1). Example: in Labrador retrievers, gene B controls black/brown coat, but gene E is epistatic, the genotype **ee** produces a yellow coat regardless of the B gene.", [2022]),
      qa(4, "Define dominant and recessive alleles.", "A **dominant** allele is one that is expressed (masks the other) in the heterozygous condition. A **recessive** allele is one that is expressed only in the homozygous condition (when both alleles are recessive).", [2019]),
    ],
    long: [
      qa(1, "A heterozygous round-yellow pea (RrYy) is self-crossed. Show the F2 phenotypic ratio with a checkerboard, and state which Mendelian law it demonstrates.", "Each parent produces four gamete types: **RY, Ry, rY, ry**. Filling the 4x4 Punnett square gives 16 combinations with the classic dihybrid result:\n\n**Phenotypic ratio = 9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green (9 : 3 : 3 : 1).**\n\nBecause the round/wrinkled gene and the yellow/green gene segregate into gametes independently of each other, the cross demonstrates Mendel's **Law of Independent Assortment**.", [2019]),
    ],
  },
  {
    id: "ch4", num: 4, title: "Biomolecules", fullTitle: "Biology for Engineers — Module 4: Biomolecules",
    concepts: [
      con("Carbohydrates", "Carbohydrates are polyhydroxy aldehydes or ketones (or compounds that yield them on hydrolysis) with C, H and O in the ratio (CH2O)n; their chief source is photosynthesis. They are monosaccharides (glucose, fructose), oligosaccharides (sucrose, lactose, maltose) or polysaccharides (starch, glycogen, cellulose). Storage forms are starch (plants) and glycogen (animal starch); structural forms are cellulose and chitin. Carbohydrates are optically active because they contain asymmetric (chiral) carbon atoms."),
      con("Lipids", "Lipids are esters of fatty acids and an alcohol; they are hydrophobic, insoluble in water but soluble in ether, benzene and chloroform. They are simple (fats, oils, waxes), compound (phospholipids, glycolipids) or derived (steroids, fatty acids). Saturated fatty acids have no double bonds, are solid, and raise cholesterol; unsaturated ones have double bonds, are liquid, and lower it. Phospholipids are amphipathic and build the cell membrane bilayer. Lipids give about 39.1 kJ per gram, more than carbohydrate or protein."),
      con("Amino acids", "An amino acid is an organic acid carrying a carboxyl (-COOH) and an amino (-NH2) group on the alpha-carbon, general formula R-CH(NH2)-COOH. There are 20 standard amino acids, about 9 of them essential (must come from diet). At low pH an amino acid is a cation, at high pH an anion, and at its isoelectric point (pI) a zwitterion (net charge zero, most stable, least soluble). Amino acids therefore act as buffers."),
      con("Protein structure", "Proteins have four structural levels. Primary is the linear amino-acid sequence joined by peptide bonds. Secondary is local folding into the alpha-helix (right-handed coil, ~3.6 residues per turn, diameter about 10 angstrom) or the beta-pleated sheet, stabilised by hydrogen bonds. Tertiary is the overall 3-D fold (H-bonds, disulphide, ionic and hydrophobic interactions). Quaternary is the assembly of more than one polypeptide. Denaturation by heat, pH or chemicals destroys the 2nd/3rd/4th levels but leaves the primary sequence intact (e.g. boiling an egg)."),
      con("Vitamins", "Vitamins are micronutrients whose deficiency causes specific diseases: vitamin D deficiency causes rickets, vitamin C causes scurvy, vitamin A causes night blindness, and vitamin B1 causes beri-beri. Fat-soluble vitamins A, D, E and K are carried by lipids."),
    ],
    mcqs: [
      mcq(1, "Carbohydrates are optically active because they contain", { a: "double bonds", b: "asymmetric (chiral) carbon atoms", c: "amino groups", d: "phosphate groups" }, "b", [2022], false),
      mcq(2, "The diameter of each coil of an alpha-helix is about", { a: "5 angstrom", b: "10 angstrom", c: "15 angstrom", d: "20 angstrom" }, "b", [], true),
      mcq(3, "Deficiency of vitamin C causes", { a: "rickets", b: "scurvy", c: "night blindness", d: "beri-beri" }, "b", [], true),
      mcq(4, "The number of essential amino acids in nature is about", { a: "5", b: "9", c: "12", d: "20" }, "b", [2022], false),
    ],
    short: [
      qa(1, "Draw the ionic and neutral structures of an amino acid and state which is stable at what pH.", "General formula **R-CH(NH2)-COOH**.\n- **Low pH (acidic):** both groups protonated, a **cation** (-NH3+, -COOH), net positive.\n- **High pH (basic):** both deprotonated, an **anion** (-NH2, -COO-), net negative.\n- **Isoelectric point (pI):** exists as a **zwitterion** (-NH3+ and -COO- together), net charge zero. This is the **most stable** form (least soluble, no migration in an electric field).", [2019]),
      qa(2, "Write a short note on denaturation of protein.", "**Denaturation** is the loss of a protein's three-dimensional structure (and therefore its function) caused by heat, extreme pH or chemicals. It destroys the **secondary, tertiary and quaternary** structures by breaking the hydrogen, ionic and disulphide interactions, but the **primary sequence (peptide bonds) stays intact**. It is often irreversible, e.g. the white of a boiled egg.", [2019]),
      qa(3, "Define essential, non-essential and partially essential amino acids.", "**Essential** amino acids cannot be made by the body and must come from the diet (e.g. valine, leucine, lysine). **Non-essential** amino acids are synthesised by the body (e.g. glycine, alanine). **Partially (semi) essential** amino acids are normally made but are needed in extra amounts during growth (e.g. arginine, histidine).", [2019]),
    ],
    long: [
      qa(1, "Define polysaccharides, classify them, and describe the structure and functions of mucopolysaccharides.", "**Polysaccharides** are carbohydrates made of more than 10 monosaccharide units joined by glycosidic bonds.\n\n**Classification:**\n- **Homopolysaccharides** (one type of monomer): **starch** (plant storage), **glycogen** (animal storage), **cellulose** (plant cell wall, beta-1,4 linked), **chitin**.\n- **Heteropolysaccharides** (more than one monomer): **mucopolysaccharides (glycosaminoglycans)** and glycoproteins.\n\n**Mucopolysaccharides (GAGs)** are long unbranched chains of repeating disaccharide units, each containing an **amino sugar** (e.g. N-acetylglucosamine) and a uronic acid; they are often sulphated and highly negatively charged.\n- **Examples:** hyaluronic acid, chondroitin sulphate, heparin, keratan sulphate.\n- **Functions:** lubricant in synovial fluid (hyaluronic acid), structural matrix of cartilage and connective tissue (chondroitin sulphate), anticoagulant (heparin), and water retention and resilience in tissues.", [2019]),
      qa(2, "Describe the four levels of protein structure with the bonds involved.", "**Primary structure:** the linear sequence of amino acids, joined by **peptide bonds**.\n**Secondary structure:** local folding into the **alpha-helix** (right-handed coil, ~3.6 residues/turn, diameter ~10 angstrom) or the **beta-pleated sheet** (extended strands side by side), stabilised by **hydrogen bonds**.\n**Tertiary structure:** the overall 3-D fold of the whole chain, held by hydrogen, **disulphide**, ionic and hydrophobic interactions.\n**Quaternary structure:** the assembly of two or more polypeptide chains into one functional protein (e.g. haemoglobin), held by the same kinds of bonds as tertiary.\n\nLoss of the 2nd/3rd/4th levels (the primary stays intact) is **denaturation**.", [], true),
    ],
  },
  {
    id: "ch5", num: 5, title: "Enzymes", fullTitle: "Biology for Engineers — Module 5: Enzymes",
    concepts: [
      con("What enzymes are", "Enzymes are biocatalysts, usually proteins, that speed up biochemical reactions without being consumed and without changing the final product or the equilibrium; they work by lowering the activation energy. The reactant is the substrate, which binds at the active site. A protein apoenzyme plus a cofactor (a metal-ion activator or an organic coenzyme) gives the active holoenzyme; a tightly bound organic cofactor is a prosthetic group."),
      con("Six classes of enzymes", "Enzymes fall into six classes (mnemonic O-T-H-I-L-L): Oxidoreductases (transfer H/O or electrons, e.g. dehydrogenases), Transferases (transfer a group such as phosphate, e.g. kinases), Hydrolases (add water to break bonds, e.g. digestive enzymes), Isomerases (rearrange a molecule), Lyases (add or remove a group non-hydrolytically, e.g. decarboxylases) and Ligases or synthetases (join molecules using ATP, e.g. DNA ligase)."),
      con("Lock-and-key vs induced fit", "Two models explain enzyme action. The lock-and-key model (Emil Fischer, 1894) says the active site and substrate have rigid complementary shapes that fit like a key in a lock. The induced-fit model (Daniel Koshland) says the active site is flexible: substrate binding induces a conformational change that moulds the site around the substrate and strains the bonds, driving the reaction. The pathway is E + S to ES to E + P."),
      con("Michaelis-Menten kinetics", "The Michaelis-Menten equation, v = Vmax[S] / (Km + [S]), describes how reaction rate depends on substrate concentration. Vmax is the maximum velocity when the enzyme is saturated. Km (the Michaelis constant) is the substrate concentration at half of Vmax: a low Km means high affinity, a high Km means low affinity. A plot of v against [S] is a rectangular hyperbola; the Lineweaver-Burk plot (1/v vs 1/[S]) linearises it."),
      con("Enzyme inhibition", "Inhibitors reduce enzyme activity. A competitive inhibitor resembles the substrate and binds the active site: it raises Km, leaves Vmax unchanged, and can be overcome by adding more substrate. A non-competitive inhibitor binds an allosteric site: it lowers Vmax, leaves Km unchanged, and cannot be overcome by more substrate. An uncompetitive inhibitor binds only the enzyme-substrate complex: it lowers both Km and Vmax."),
      con("Factors affecting activity", "Enzyme activity depends on temperature (rises to an optimum near 37 C in humans, then falls sharply as the enzyme denatures, a bell curve), pH (each enzyme has an optimum, e.g. pepsin ~2, trypsin ~8), substrate concentration (rises then plateaus at Vmax), enzyme concentration (proportional to rate when substrate is in excess), and the presence of inhibitors or activators."),
    ],
    mcqs: [
      mcq(1, "Km in the Michaelis-Menten model is the substrate concentration at", { a: "Vmax", b: "half of Vmax", c: "zero velocity", d: "twice Vmax" }, "b", [], true),
      mcq(2, "A competitive inhibitor changes Km and Vmax as follows", { a: "Km increases, Vmax unchanged", b: "Km unchanged, Vmax decreases", c: "both decrease", d: "both increase" }, "a", [2022], false),
      mcq(3, "The lock-and-key model of enzyme action was proposed by", { a: "Koshland", b: "Emil Fischer", c: "Michaelis", d: "Menten" }, "b", [], true),
      mcq(4, "Enzymes speed up reactions by", { a: "raising activation energy", b: "lowering activation energy", c: "changing the equilibrium", d: "being consumed" }, "b", [], true),
    ],
    short: [
      qa(1, "Explain the variation of enzyme activity with pH and temperature (with a graph).", "Both give a **bell-shaped curve** with an optimum.\n- **Temperature:** activity rises with temperature up to an **optimum** (~37 C in humans) as molecular collisions increase, then falls sharply because the enzyme **denatures** at high temperature.\n- **pH:** each enzyme has an **optimum pH** (pepsin ~2, trypsin ~8); above or below it the active site's charges change and activity drops.\n\n```\n rate |     .-''-.   <- optimum\n      |   .'     '.\n      | .'         '.\n      |/____________\\__ pH / temperature\n```", [2019]),
      qa(2, "What are the steps from enzyme-substrate complex formation to product release?", "The substrate binds the active site to form the **enzyme-substrate (ES) complex** (in the induced-fit model the site moulds around it). The bound substrate's bonds are **strained**, lowering the activation energy; the substrate is converted to **product** while still bound (EP complex). The product then **leaves** the active site, and the unchanged enzyme is **free to bind another substrate**. Overall: E + S to ES to EP to E + P.", [2022]),
    ],
    long: [
      qa(1, "Explain how competitive, uncompetitive and non-competitive inhibitors act on Km and Vmax. List the factors affecting enzyme activity.", "**Enzyme inhibition** is a decrease in enzyme activity caused by an inhibitor binding the enzyme.\n\n**1. Competitive inhibition:** the inhibitor resembles the substrate and binds the **active site**, competing with the substrate. It can be **overcome by increasing [S]**. Effect: **Km increases**, **Vmax unchanged** (e.g. malonate on succinate dehydrogenase).\n\n**2. Non-competitive inhibition:** the inhibitor binds an **allosteric site**, changing the enzyme's shape; it is **not** overcome by more substrate. Effect: **Vmax decreases**, **Km unchanged** (e.g. heavy-metal ions Pb2+, Hg2+).\n\n**3. Uncompetitive inhibition:** the inhibitor binds **only the ES complex**. Effect: **both Km and Vmax decrease**.\n\n| Type | Binds | Km | Vmax | Reversed by more [S]? |\n|---|---|:--:|:--:|:--:|\n| Competitive | active site | up | same | Yes |\n| Non-competitive | allosteric | same | down | No |\n| Uncompetitive | ES complex | down | down | No |\n\n**Factors affecting enzyme activity:** temperature (optimum ~37 C, denatures above), pH (each has an optimum), substrate concentration (saturates at Vmax), enzyme concentration (proportional when substrate is in excess), and inhibitors/activators.", [2022, 2019]),
      qa(2, "Deduce the rate of enzyme action using the Michaelis-Menten model and define Km and Vmax.", "For the scheme E + S to (k1, k-1) ES to (k2) E + P, assuming the steady state d[ES]/dt = 0, the rate is:\n\n$$v = \\frac{V_{max}[S]}{K_m + [S]}, \\quad K_m = \\frac{k_{-1}+k_2}{k_1}$$\n\n- **Vmax** is the maximum velocity, reached when the enzyme is fully saturated with substrate.\n- **Km (Michaelis constant)** is the substrate concentration at which v = Vmax/2, so it measures the enzyme's **affinity** (low Km = high affinity).\n\nA plot of v vs [S] is a **rectangular hyperbola**; the **Lineweaver-Burk** double-reciprocal plot (1/v vs 1/[S]) gives a straight line for finding Km and Vmax.", [2019]),
    ],
  },
  {
    id: "ch6", num: 6, title: "Information Transfer", fullTitle: "Biology for Engineers — Module 6: Information Transfer (DNA, Central Dogma)",
    concepts: [
      con("DNA and the central dogma", "DNA (deoxyribonucleic acid) was first extracted by Friedrich Miescher in 1869 (he called it nuclein); Watson and Crick proposed its double helix in 1953. The central dogma describes information flow: DNA is copied by replication, transcribed into RNA, and translated into protein. Some retroviruses run reverse transcription (RNA to DNA)."),
      con("DNA structure", "A nucleotide is a base plus a pentose sugar (deoxyribose) plus a phosphate; a base plus sugar alone is a nucleoside. The bases are purines adenine (A) and guanine (G, double ring) and pyrimidines cytosine (C) and thymine (T, single ring); RNA uses uracil (U) for thymine. By Chargaff's rule A pairs with T (two H-bonds) and G pairs with C (three H-bonds), so if A is 30% then T is 30% and G = C = 20%. The double helix is two antiparallel right-handed strands (~10 bp per turn) with the sugar-phosphate backbone outside and bases inside."),
      con("DNA replication", "Replication is semi-conservative (proved by Meselson and Stahl, 1958): each new molecule keeps one old and one new strand. Initiation: helicase unwinds DNA at the origin to make a replication fork; single-strand binding proteins stabilise it and primase lays an RNA primer. Elongation: DNA polymerase adds nucleotides only 5' to 3', so the leading strand is continuous while the lagging strand is made in Okazaki fragments later joined by DNA ligase. Termination: the forks meet, primers are removed and gaps are sealed."),
      con("Transcription", "Transcription copies DNA into RNA, catalysed by RNA polymerase (in eukaryotes RNA Pol II makes the mRNA precursor). It proceeds by initiation at the promoter (TATA box), elongation, and termination. In eukaryotes the mRNA is then processed: a 5' cap and poly-A tail are added and introns are removed by splicing, joining the exons."),
      con("Translation and the genetic code", "Translation builds protein on ribosomes. A codon is three mRNA nucleotides coding one amino acid; with 64 codons for 20 amino acids the code is degenerate. The start codon is AUG (methionine) and the stop codons are UAA, UAG and UGA. tRNA carries amino acids and its anticodon pairs with the codon. Translation runs through initiation, elongation and termination. The three RNA types are mRNA (the message), tRNA (carries amino acids) and rRNA (structural part of the ribosome)."),
    ],
    mcqs: [
      mcq(1, "The initiation (start) codon is", { a: "UAA", b: "UGA", c: "AUG", d: "UAG" }, "c", [], true),
      mcq(2, "A codon consists of how many nucleotides?", { a: "1", b: "2", c: "3", d: "4" }, "c", [], true),
      mcq(3, "In a double-stranded DNA with 30% adenine, the percentage of guanine is", { a: "30", b: "40", c: "20", d: "70" }, "c", [], true),
      mcq(4, "DNA replication is", { a: "conservative", b: "semi-conservative", c: "dispersive", d: "random" }, "b", [], true),
      mcq(5, "The enzyme that transcribes the mRNA precursor in eukaryotes is", { a: "RNA polymerase I", b: "RNA polymerase II", c: "DNA polymerase", d: "helicase" }, "b", [], true),
    ],
    short: [
      qa(1, "State Chargaff's base-pairing rule and give the start and stop codons.", "**Chargaff's rule:** in double-stranded DNA, adenine pairs with thymine (**A = T**, two hydrogen bonds) and guanine pairs with cytosine (**G = C**, three hydrogen bonds), so A% = T% and G% = C%. **Start codon:** AUG (methionine). **Stop codons:** UAA, UAG, UGA.", [], true),
      qa(2, "Differentiate transcription and translation.", "**Transcription** copies a DNA template into RNA, in the nucleus (eukaryotes), catalysed by **RNA polymerase**; product is mRNA. **Translation** decodes the mRNA into a protein, on the **ribosome**, using tRNA whose anticodons read the codons; product is a polypeptide. Both proceed by initiation, elongation and termination.", [], true),
      qa(3, "Write a short note on the structure of tRNA.", "Transfer RNA (tRNA) is a small RNA that carries a specific amino acid to the ribosome. It folds into a **clover-leaf** secondary structure (an L-shape in 3-D) with an **amino-acid acceptor end** (the 3' CCA end) and an **anticodon loop** whose three bases pair with the complementary mRNA codon, ensuring the correct amino acid is added.", [2019]),
    ],
    long: [
      qa(1, "Elaborately explain DNA replication (initiation, elongation, termination) with a diagram.", "DNA replication is **semi-conservative** (proved by **Meselson and Stahl, 1958**): each daughter molecule has one parental and one new strand.\n\n**1. Initiation:** at the **origin of replication**, **helicase** unwinds the double helix by breaking hydrogen bonds; **single-strand binding proteins** keep the strands apart; **topoisomerase** relieves supercoiling; a **replication fork** forms. **Primase** lays down a short RNA primer.\n\n**2. Elongation:** **DNA polymerase** adds nucleotides only in the **5' to 3'** direction, reading the template 3' to 5'.\n- **Leading strand:** synthesised **continuously** toward the fork.\n- **Lagging strand:** synthesised **discontinuously** as **Okazaki fragments**, each needing its own primer; primers are later removed and the fragments joined by **DNA ligase**.\n\n**3. Termination:** the replication forks meet, the last primers are removed and the gaps are sealed, giving two identical daughter DNA molecules.\n\n```\n            ----------------->  leading (continuous)\n   5'----- origin\n        | helicase unwinds\n   3'-----\n            ---  ---  ---   lagging (Okazaki fragments, joined by ligase)\n```", [2019]),
    ],
  },
  {
    id: "ch7", num: 7, title: "Macromolecular Analysis", fullTitle: "Biology for Engineers — Module 7: Macromolecular Analysis (DNA Packaging)",
    concepts: [
      con("Why DNA must be packaged", "About 2 metres of DNA must fit inside a nucleus only ~10 micrometre across. Eukaryotes achieve this through several levels of folding around histone proteins, condensing the DNA roughly ten-thousand-fold while keeping genes accessible."),
      con("The nucleosome", "The nucleosome is the basic packaging unit: about 147 base pairs of DNA wrapped roughly 1.65 turns around a histone octamer. The octamer is eight histone proteins, two copies each of H2A, H2B, H3 and H4. A separate linker histone, H1, binds the DNA between nucleosomes (it is not part of the core octamer). Under the electron microscope this looks like beads on a string."),
      con("Levels of packaging", "Packaging proceeds in stages: the 2-nm double helix wraps into nucleosomes (the 11-nm beads-on-a-string), which coil into a 30-nm chromatin fibre (solenoid), which loops onto a protein scaffold to form looped domains, which condense further into the visible chromosome (about 1400 nm at metaphase)."),
      con("Histones and chromatin states", "Histones are small, basic proteins rich in arginine and lysine, so they are positively charged and bind the negatively charged DNA backbone. The DNA-plus-histone complex is chromatin. Loosely packed, transcriptionally active chromatin is euchromatin; tightly packed, inactive chromatin is heterochromatin."),
    ],
    mcqs: [
      mcq(1, "The number of histone proteins in a nucleosome core is", { a: "4", b: "6", c: "8", d: "10" }, "c", [2019], false),
      mcq(2, "The histone that binds linker DNA between nucleosomes is", { a: "H1", b: "H2A", c: "H3", d: "H4" }, "a", [], true),
      mcq(3, "Transcriptionally active, loosely packed chromatin is called", { a: "heterochromatin", b: "euchromatin", c: "nucleosome", d: "solenoid" }, "b", [], true),
    ],
    short: [
      qa(1, "Write a short note on the structure of a nucleosome.", "The **nucleosome** is the basic unit of DNA packaging: about **147 base pairs** of DNA wrapped ~1.65 turns around a **histone octamer** (two copies each of **H2A, H2B, H3, H4**, i.e. eight histones). The linker histone **H1** binds the DNA between adjacent nucleosomes but is not part of the core. In the electron microscope a chain of nucleosomes looks like **beads on a string**.", [2019]),
      qa(2, "Distinguish euchromatin and heterochromatin.", "**Euchromatin** is loosely packed, lightly staining and **transcriptionally active** (its genes can be expressed). **Heterochromatin** is tightly packed, darkly staining and **transcriptionally inactive**. Both are made of the same DNA-plus-histone material; they differ in how condensed they are.", [], true),
    ],
    long: [
      qa(1, "Explain how DNA is packaged in a eukaryotic chromosome, with diagrams.", "About 2 m of DNA is condensed into a ~10 micrometre nucleus through successive levels of folding around **histones**:\n\n```\n DNA double helix (2 nm)\n     | wraps around a histone octamer\n NUCLEOSOME (beads on a string, 11 nm)\n     | coiling\n 30-nm chromatin fibre (solenoid)\n     | looping onto a scaffold\n looped domains\n     | further condensation\n CHROMOSOME (~1400 nm at metaphase)\n```\n\n- **Nucleosome:** ~147 bp of DNA wrapped ~1.65 turns around a **histone octamer** (2x H2A, H2B, H3, H4); **H1** binds the linker DNA.\n- The nucleosome string coils into the **30-nm fibre**, which forms **looped domains** on a protein scaffold.\n- These loops condense into the metaphase **chromosome**.\n\nHistones are positively charged (arginine/lysine-rich) and so bind the negatively charged DNA. Active regions stay loosely packed (**euchromatin**), inactive ones tightly packed (**heterochromatin**).", [2019]),
    ],
  },
  {
    id: "ch8", num: 8, title: "Metabolism & Bioenergetics", fullTitle: "Biology for Engineers — Module 8: Metabolism and Bioenergetics",
    concepts: [
      con("Metabolism", "Metabolism is the sum of all chemical reactions in a cell. Anabolism builds molecules up (synthesis) and is endergonic (e.g. photosynthesis, protein synthesis). Catabolism breaks molecules down and is exergonic (e.g. respiration). A pathway that does both is amphibolic (e.g. the Krebs cycle). Living systems are open systems that take in energy and release heat and waste to keep their internal entropy low."),
      con("ATP, the energy currency", "ATP (adenosine triphosphate) is the energy currency of the cell. It is adenine plus a ribose sugar plus three phosphate groups (alpha, beta, gamma); the terminal phosphate bonds are high-energy. Hydrolysis of ATP to ADP + Pi releases about 7.3 kcal/mol, which powers muscle contraction, active transport, biosynthesis, cell division and signalling."),
      con("Photosynthesis", "Photosynthesis fixes carbon: 6 CO2 + 6 H2O, driven by light and chlorophyll, give C6H12O6 + 6 O2. The light reaction occurs in the thylakoid membrane and uses water and light to make ATP, NADPH and oxygen. The dark (Calvin) reaction occurs in the stroma and uses CO2 plus the ATP and NADPH from the light reaction to build glucose. The central metal of chlorophyll is magnesium."),
      con("Cellular respiration", "Cellular respiration releases energy from glucose: glucose to CO2 + H2O + ATP, in the mitochondria of eukaryotes. It runs in three stages: glycolysis in the cytoplasm, the Krebs cycle in the matrix, and the electron transport chain on the inner membrane. Aerobic respiration of one glucose yields about 36 to 38 ATP."),
      con("Glucose interconversions", "The body interconverts glucose and glycogen as needed: glycogenesis makes glycogen from glucose, glycogenolysis breaks glycogen back to glucose, and gluconeogenesis makes glucose from non-carbohydrate sources. Exergonic processes release energy (negative delta G, spontaneous); endergonic processes absorb energy (positive delta G)."),
    ],
    mcqs: [
      mcq(1, "Respiration in eukaryotic cells occurs mainly in the", { a: "nucleus", b: "ribosome", c: "chloroplast", d: "mitochondria" }, "d", [], true),
      mcq(2, "The central metal atom of chlorophyll is", { a: "iron", b: "magnesium", c: "calcium", d: "zinc" }, "b", [], true),
      mcq(3, "The Calvin cycle uses which products of the light reaction?", { a: "oxygen and water", b: "ATP and NADPH", c: "glucose and CO2", d: "ADP and NADP+" }, "b", [2019], false),
      mcq(4, "A pathway that synthesises compounds is", { a: "catabolic", b: "anabolic", c: "amphibolic", d: "exergonic" }, "b", [], true),
    ],
    short: [
      qa(1, "Distinguish exergonic and endergonic processes.", "An **exergonic** process **releases** energy to the surroundings (negative delta G) and is spontaneous, e.g. cellular respiration. An **endergonic** process **absorbs** energy (positive delta G) and is non-spontaneous, requiring an input, e.g. photosynthesis or biosynthesis. Cells couple endergonic reactions to ATP hydrolysis to drive them.", [], true),
      qa(2, "Define glycogenesis, glycogenolysis and gluconeogenesis.", "**Glycogenesis** is the synthesis of **glycogen from glucose** (storing glucose). **Glycogenolysis** is the breakdown of **glycogen back into glucose** (releasing stored glucose). **Gluconeogenesis** is the synthesis of **glucose from non-carbohydrate** precursors (such as amino acids, lactate or glycerol).", [2019]),
      qa(3, "Give the location and products of the light and dark reactions of photosynthesis, and the central element of chlorophyll.", "**Light reaction:** in the **thylakoid membrane**; uses water and light to produce **ATP, NADPH and oxygen**. **Dark (Calvin) reaction:** in the **stroma**; uses CO2 with the ATP and NADPH from the light reaction to make **glucose**. The central element of chlorophyll is **magnesium (Mg)**.", [2019]),
    ],
    long: [
      qa(1, "Explain ATP as the energy currency of the cell, with its structure and functions.", "**ATP (adenosine triphosphate)** is the universal energy currency of the cell, the molecule that stores and delivers energy for nearly all cellular work.\n\n**Structure:** ATP is made of **adenine** (a nitrogenous base) + **ribose** (a five-carbon sugar) + **three phosphate groups** (alpha, beta, gamma). The two terminal phosphate bonds are **high-energy bonds**.\n\n```\n Adenine - Ribose - P ~ P ~ P    ( ~ = high-energy bond )\n```\n\n**Energy release:** hydrolysing the terminal bond gives **ATP to ADP + Pi + energy** (about 7.3 kcal/mol). The reaction is reversible, so ATP is continually regenerated by respiration and photosynthesis.\n\n**Functions:** it powers muscle contraction, **active transport** across membranes, **biosynthesis** of macromolecules, cell division, and nerve signalling and other energy-requiring processes. Because it is constantly made and spent, ATP acts like cash, an immediate, spendable form of energy.", [], true),
    ],
  },
  {
    id: "ch9", num: 9, title: "Microbiology", fullTitle: "Biology for Engineers — Module 9: Microbiology",
    concepts: [
      con("What microbiology studies", "Microbiology is the study of microorganisms: bacteria, viruses, fungi, protozoa and algae. Antonie van Leeuwenhoek (1676) is the father of microbiology (he first observed microbes). Louis Pasteur (1857) showed that fermentation is caused by microbial activity and disproved spontaneous generation."),
      con("Bacteria vs viruses", "Bacteria are living, cellular prokaryotes with a peptidoglycan cell wall and DNA (plus plasmids); they reproduce independently by binary fission and are treated with antibiotics. Viruses are non-cellular (acellular), on the border of living and non-living, carry either DNA or RNA inside a protein capsid, and can reproduce only inside a host cell; they are countered with antivirals and vaccines. A useful virus is the bacteriophage, which kills bacteria."),
      con("Immunity", "Immunity defends the body against pathogens. Innate (natural) immunity is present from birth, non-specific and immediate, using barriers like skin and mucus, phagocytes and inflammation. Adaptive (acquired) immunity develops after exposure, is specific, and has memory, using antibodies and B-cells and T-cells; it is the basis of vaccination."),
      con("Antibiotics, cancer and stem cells", "Antibiotics are substances produced by microbes that kill or inhibit other microbes; penicillin was discovered by Alexander Fleming in 1928 from the mould Penicillium. They treat bacterial, not viral, infections. Cancer is uncontrolled, abnormal cell division (loss of cell-cycle control) that forms malignant tumours and can spread (metastasise). Stem cells are unspecialised cells that can self-renew and differentiate into specialised cell types."),
    ],
    mcqs: [
      mcq(1, "The cell wall of a bacterium is made of", { a: "cellulose", b: "chitin", c: "peptidoglycan", d: "lipid" }, "c", [], true),
      mcq(2, "Penicillin was discovered by", { a: "Louis Pasteur", b: "Alexander Fleming", c: "van Leeuwenhoek", d: "Robert Koch" }, "b", [], true),
      mcq(3, "The most common growth medium for culturing microbes is", { a: "agar plates", b: "distilled water", c: "ethanol", d: "saline only" }, "a", [], true),
      mcq(4, "Antibiotics are effective against", { a: "viruses", b: "bacteria", c: "all microbes equally", d: "prions" }, "b", [], true),
    ],
    short: [
      qa(1, "Distinguish bacteria from viruses and name one beneficial virus.", "**Bacteria** are living, **cellular** prokaryotes with a **peptidoglycan** wall and DNA, reproduce **independently** by binary fission, and are treated with **antibiotics**. **Viruses** are **acellular**, on the border of living and non-living, carry **DNA or RNA** in a protein capsid, reproduce **only inside a host cell**, and are countered with antivirals/vaccines. A **beneficial virus** is the **bacteriophage**, which infects and kills harmful bacteria.", [2019]),
      qa(2, "Differentiate innate and adaptive immunity.", "**Innate (natural) immunity** is present from birth, **non-specific**, acts immediately, and has **no memory** (skin, mucus, phagocytes, inflammation). **Adaptive (acquired) immunity** develops **after exposure**, is **specific** to a pathogen, and has **memory** (antibodies, B-cells and T-cells), which is why vaccination works.", [2019]),
      qa(3, "Write a short note on stem cells.", "**Stem cells** are unspecialised cells with two defining abilities: they can **self-renew** (divide to make more stem cells) and **differentiate** into specialised cell types. They are **embryonic** (can form any cell type) or **adult/tissue** stem cells (more limited). They are central to growth, tissue repair and regenerative medicine.", [2019]),
    ],
    long: [
      qa(1, "Describe cancer biology, define stem cells and their functions, and explain what antibiotics are and who discovered them.", "**Cancer:** cancer is **uncontrolled, abnormal cell division** caused by a loss of normal cell-cycle control (often through mutations in genes that regulate growth). The dividing cells form a **malignant tumour** that invades nearby tissue and can **metastasise** (spread to distant sites through blood or lymph). Normal checkpoints and programmed cell death (apoptosis) fail.\n\n**Stem cells:** unspecialised cells that can **self-renew** and **differentiate** into specialised cell types. **Embryonic** stem cells can become any cell type; **adult** stem cells repair specific tissues. Their function is growth, tissue maintenance and repair, and they are the basis of regenerative medicine.\n\n**Antibiotics:** substances produced by microbes that **kill or inhibit other microbes**; they treat **bacterial** (not viral) infections. **Penicillin**, the first antibiotic, was discovered by **Alexander Fleming in 1928** from the mould **Penicillium**.", [2019]),
    ],
  },
];

const totals = chapters.reduce((t, c) => {
  t.mcqs += c.mcqs.length; t.short += c.short.length; t.long += c.long.length; return t;
}, { mcqs: 0, short: 0, long: 0 });
const maxPYQ = Math.max(...chapters.flatMap((c) => [...c.mcqs, ...c.short, ...c.long].map((q) => (q.years?.length || 0))));

const out = {
  subject: "Biology",
  generatedFrom: "Biology for Engineers master + practice notes (MAKAUT BSC401; PYQs BSC401-2022, BS-EE-301-2019, BS-BIO-301-2019)",
  chapterCount: chapters.length,
  totals,
  maxPYQFrequency: maxPYQ,
  chapters: chapters.map((c) => ({ ...c, file: `${c.num} ${c.title}.md` })),
};

writeFileSync(new URL("../public/data/biology.json", import.meta.url), JSON.stringify(out, null, 1));
console.log(`biology.json written: ${chapters.length} chapters, ${totals.mcqs} MCQs, ${totals.short} short, ${totals.long} long.`);
